package com.example.utilityapp.currency

data class CurrencyInfo(
    val name: String,
    val symbol: String
)

val ALL_CURRENCIES: Map<String, CurrencyInfo> = mapOf(
    "USD" to CurrencyInfo("US Dollar", "$"),
    "EUR" to CurrencyInfo("Euro", "€"),
    "GBP" to CurrencyInfo("British Pound", "£"),
    "JPY" to CurrencyInfo("Japanese Yen", "¥"),
    "AUD" to CurrencyInfo("Australian Dollar", "A$"),
    "CAD" to CurrencyInfo("Canadian Dollar", "C$"),
    "CHF" to CurrencyInfo("Swiss Franc", "CHF"),
    "CNY" to CurrencyInfo("Chinese Yuan", "¥"),
    "INR" to CurrencyInfo("Indian Rupee", "₹"),
    "PKR" to CurrencyInfo("Pakistani Rupee", "₨"),
    "AED" to CurrencyInfo("UAE Dirham", "د.إ"),
    "SAR" to CurrencyInfo("Saudi Riyal", "ر.س"),
    "QAR" to CurrencyInfo("Qatari Riyal", "ر.ق"),
    "KWD" to CurrencyInfo("Kuwaiti Dinar", "د.ك"),
    "BHD" to CurrencyInfo("Bahraini Dinar", "د.ب"),
    "OMR" to CurrencyInfo("Omani Rial", "ر.ع."),
    "JOD" to CurrencyInfo("Jordanian Dinar", "د.أ"),
    "TRY" to CurrencyInfo("Turkish Lira", "₺"),
    "SEK" to CurrencyInfo("Swedish Krona", "kr"),
    "NOK" to CurrencyInfo("Norwegian Krone", "kr"),
    "DKK" to CurrencyInfo("Danish Krone", "kr"),
    "PLN" to CurrencyInfo("Polish Zloty", "zł"),
    "CZK" to CurrencyInfo("Czech Koruna", "Kč"),
    "HUF" to CurrencyInfo("Hungarian Forint", "Ft"),
    "RON" to CurrencyInfo("Romanian Leu", "lei"),
    "RUB" to CurrencyInfo("Russian Ruble", "₽"),
    "UAH" to CurrencyInfo("Ukrainian Hryvnia", "₴"),
    "KRW" to CurrencyInfo("South Korean Won", "₩"),
    "SGD" to CurrencyInfo("Singapore Dollar", "S$"),
    "HKD" to CurrencyInfo("Hong Kong Dollar", "HK$"),
    "TWD" to CurrencyInfo("Taiwan Dollar", "NT$"),
    "THB" to CurrencyInfo("Thai Baht", "฿"),
    "MYR" to CurrencyInfo("Malaysian Ringgit", "RM"),
    "IDR" to CurrencyInfo("Indonesian Rupiah", "Rp"),
    "PHP" to CurrencyInfo("Philippine Peso", "₱"),
    "VND" to CurrencyInfo("Vietnamese Dong", "₫"),
    "BDT" to CurrencyInfo("Bangladeshi Taka", "৳"),
    "LKR" to CurrencyInfo("Sri Lankan Rupee", "Rs"),
    "NPR" to CurrencyInfo("Nepalese Rupee", "रू"),
    "ZAR" to CurrencyInfo("South African Rand", "R"),
    "NGN" to CurrencyInfo("Nigerian Naira", "₦"),
    "EGP" to CurrencyInfo("Egyptian Pound", "£E"),
    "KES" to CurrencyInfo("Kenyan Shilling", "KSh"),
    "GHS" to CurrencyInfo("Ghanaian Cedi", "₵"),
    "MAD" to CurrencyInfo("Moroccan Dirham", "د.م."),
    "BRL" to CurrencyInfo("Brazilian Real", "R$"),
    "MXN" to CurrencyInfo("Mexican Peso", "$"),
    "ARS" to CurrencyInfo("Argentine Peso", "$"),
    "COP" to CurrencyInfo("Colombian Peso", "$"),
    "CLP" to CurrencyInfo("Chilean Peso", "$"),
    "PEN" to CurrencyInfo("Peruvian Sol", "S/"),
    "NZD" to CurrencyInfo("New Zealand Dollar", "NZ$"),
    "ILS" to CurrencyInfo("Israeli Shekel", "₪"),
    "KZT" to CurrencyInfo("Kazakhstani Tenge", "₸"),
    "MNT" to CurrencyInfo("Mongolian Tugrik", "₮"),
    "GEL" to CurrencyInfo("Georgian Lari", "₾"),
    "AMD" to CurrencyInfo("Armenian Dram", "֏"),
    "AZN" to CurrencyInfo("Azerbaijani Manat", "₼"),
    "IRR" to CurrencyInfo("Iranian Rial", "﷼"),
    "IQD" to CurrencyInfo("Iraqi Dinar", "ع.د"),
    "LBP" to CurrencyInfo("Lebanese Pound", "ل.ل"),
    "BGN" to CurrencyInfo("Bulgarian Lev", "лв"),
    "HRK" to CurrencyInfo("Croatian Kuna", "kn"),
    "RSD" to CurrencyInfo("Serbian Dinar", "дин."),
    "ISK" to CurrencyInfo("Icelandic Króna", "kr"),
    "UZS" to CurrencyInfo("Uzbekistani Som", "лв"),
    "TJS" to CurrencyInfo("Tajikistani Somoni", "SM"),
    "KGS" to CurrencyInfo("Kyrgyzstani Som", "лв"),
    "TMT" to CurrencyInfo("Turkmenistan Manat", "T"),
    "FJD" to CurrencyInfo("Fijian Dollar", "FJ$"),
    "PGK" to CurrencyInfo("Papua New Guinea Kina", "K"),
    "XAF" to CurrencyInfo("Central African CFA", "FCFA"),
    "XOF" to CurrencyInfo("West African CFA", "CFA")
)